### ISSUE TITLE
Unexpected alignment behavior

### ISSUE THREAD

**Issue by ajwilk** [ShalekLab/tcrgo#1]
Hi there,
Thanks so much for putting together such a well-documented pipeline! I have data from a tiny sequencing run I'm trying to run through the workflow on Terra, but it's failing because of poor alignment. 

Error occurs in ```filter_queries```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scripts/filter_queries.py", line 133, in <module>
    main(args)
  File "/scripts/filter_queries.py", line 43, in main
    io.output_grouped_VJ_queries(id_queries, args.workers, args.output_path)
  File "/scripts/tcrgo/log.py", line 71, in time_wrapper
    output = function(*args, **kwargs)
  File "/scripts/tcrgo/io.py", line 191, in output_grouped_VJ_queries
    remainder = num_queries % partition_size
ZeroDivisionError: integer division or modulo by zero
```

But appears due to the fact that basically none of my reads are aligning: 
```
2320997 reads; of these:
  2320997 (100.00%) were unpaired; of these:
    2320986 (100.00%) aligned 0 times
    1 (0.00%) aligned exactly 1 time
    10 (0.00%) aligned >1 times
0.00% overall alignment rate
```

**Expected behavior**
In case these reads were somehow non-TCR reads (biologically implausible given the read 1 primer is specific to the constant region, but nonetheless...) I aligned the sequencing run with STAR to the full human genome: 
```
                                 Started job on |	May 24 16:48:21
                             Started mapping on |	May 24 16:49:09
                                    Finished on |	May 24 16:53:24
       Mapping speed, Million of reads per hour |	32.77

                          Number of input reads |	2321001
                      Average input read length |	150
                                    UNIQUE READS:
                   Uniquely mapped reads number |	2031867
                        Uniquely mapped reads % |	87.54%
                          Average mapped length |	90.65
                       Number of splices: Total |	187506
            Number of splices: Annotated (sjdb) |	263
                       Number of splices: GT/AG |	138314
                       Number of splices: GC/AG |	185
                       Number of splices: AT/AC |	2
               Number of splices: Non-canonical |	49005
                      Mismatch rate per base, % |	1.31%
                         Deletion rate per base |	0.01%
                        Deletion average length |	1.07
                        Insertion rate per base |	0.00%
                       Insertion average length |	1.02
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	277735
             % of reads mapped to multiple loci |	11.97%
        Number of reads mapped to too many loci |	11398
             % of reads mapped to too many loci |	0.49%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	0.00%
                     % of reads unmapped: other |	0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%
```
Not only is the alignment rate good, but further examination reveals >99% reads map to human TCR genes. 

**Additional context**
 Input data:
```--fasta```: I'm using the fasta from [here](https://github.com/mitlovelab/SeqWell-TCR/blob/master/TCR_fastqprocessing/humanTCR/humanTCR.fa) 
```--sequence_data```: I'm using 2 raw .fastq.gz for input in the format ```["gs://path/V3_S0_L001_I1_001.fastq.gz","gs://path/V3_S0_L001_R1_001.fastq.gz"]```. On the off chance I misunderstood this order, I tried putting the R1 file first and it failed much earlier, as expected. 

Logs from ```call-alignment``` [here](https://github.com/ShalekLab/tcrgo/files/6535630/alignment.log)

Any idea what could be going wrong? Happy to share more info or data if helpful. Thanks so much!

**Comment by snyquist2** [comment]
Apologies for the delay! I also just ran into this problem - it looks like when the two fastq input option is used (something we hadn't previously extensively tested), bowtie2 only finds alignments when the reverse complement is allowed. I just updated the call to bowtie2 to allow for reverse complement alignments and that step is now working for me.

This is a quick patch that should probably be tested more carefully... but let me know if it does not work for you!

I am having trouble now with the BC/UMI index read also being read as a reverse complement the way I ran bcl2fastq so the BC/UMI collapse step isn't working, but hopefully that is not an issue for you!  If it is, I'll let you know if I find a fix.

**Comment by ajwilk** [comment]
Thanks so much @snyquist2!! This totally makes sense. So now the alignment output certainly has changed, but it looks like there's a ton of multi-mappers (not what I was expecting based on my toy STAR alignment above): 
```
1380061 reads; of these:
  1380061 (100.00%) were unpaired; of these:
    38458 (2.79%) aligned 0 times
    32703 (2.37%) aligned exactly 1 time
    1308900 (94.84%) aligned >1 times
97.21% overall alignment rate
```
Are these the expected alignment rates? 

Also, the pipeline is failing in a new place for me (still in ```call_alignment```): 
```
02:00:35 - INFO: Tagging the merged BAM with TRA/TRB exon info.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scripts/alignment.py", line 222, in <module>
    main(args)
  File "/scripts/alignment.py", line 123, in main
    ds.fauxtag_exons(bam_merged, bam_exontagged)
  File "/scripts/tcrgo/dropseq_tools.py", line 405, in fauxtag_exons
    raise Exception(f"Unknown gene in {query.reference_name}!")
Exception: Unknown gene in M22198|TRDV1*01|!
2021/06/07 02:04:10 Starting delocalization.
2021/06/07 02:04:11 Delocalization script execution started...
2021/06/07 02:04:11 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-d8b64044-a999-46bf-846b-b52b2a9a1b7c/6b9a7753-0a6d-4491-b3e5-e31da55d6f76/TCRGO/d2a2f36a-0807-4988-bb42-c2311413205b/call-alignment/memory_retry_rc
2021/06/07 02:04:11 Delocalizing output /cromwell_root/rc -> gs://fc-d8b64044-a999-46bf-846b-b52b2a9a1b7c/6b9a7753-0a6d-4491-b3e5-e31da55d6f76/TCRGO/d2a2f36a-0807-4988-bb42-c2311413205b/call-alignment/rc
2021/06/07 02:04:12 Delocalizing output /cromwell_root/stdout -> gs://fc-d8b64044-a999-46bf-846b-b52b2a9a1b7c/6b9a7753-0a6d-4491-b3e5-e31da55d6f76/TCRGO/d2a2f36a-0807-4988-bb42-c2311413205b/call-alignment/stdout
2021/06/07 02:04:13 Delocalizing output /cromwell_root/stderr -> gs://fc-d8b64044-a999-46bf-846b-b52b2a9a1b7c/6b9a7753-0a6d-4491-b3e5-e31da55d6f76/TCRGO/d2a2f36a-0807-4988-bb42-c2311413205b/call-alignment/stderr
2021/06/07 02:04:15 Delocalizing output /cromwell_root/out/pregnancy_test2_repairedsorted.bam -> gs://fc-d8b64044-a999-46bf-846b-b52b2a9a1b7c/6b9a7753-0a6d-4491-b3e5-e31da55d6f76/TCRGO/d2a2f36a-0807-4988-bb42-c2311413205b/call-alignment/out/pregnancy_test2_repairedsorted.bam
Required file output '/cromwell_root/out/pregnancy_test2_repairedsorted.bam' does not exist.
```

I don't see anything suspicious with the syntax of this gene name in the reference I'm using (from [here](https://github.com/mitlovelab/SeqWell-TCR/blob/master/TCR_fastqprocessing/humanTCR/humanTCR.fa)). 

```
>M22198|TRDV1*01|
gcccagaaggttactcaagcccagtcatcagtatccatgccagtgaggaaagcagtcacc
ctgaactgcctgtatgaaacaagttggtggtcatattatattttt
tggtacaagcaacttcccagcaaagagatgattttccttattcgccagggt
tctgatgaacagaatgcaaaaagtggtcgctattctgtcaacttc
aagaaagcagcgaaatccgtcgccttaaccatttcagccttacagctagaagattcagca
aagtacttttgtgctcttggggaact
```
Though I suppose I can just dump the TRD* and TRG* genes from the reference since they shouldn't be sequenced anyways, it'd be nice to know what's causing this. Also, let me know if you recommend using a different human reference than the one in the original repo.

any thoughts? thanks again so much for your help! I'll let you know if I run into the BC/UMI collapse issue, the core ran bcl2fastq on these so I'm actually not sure what to expect at that stage!

**Comment by snyquist2** [comment]
@ajwilk I keep missing the notifications on this post - sorry for the delay again!

I think you should remove the TRD* and TRG* genes from the reference for now, this is an edge case we must have forgotten to incorporate (gene names that don't match the TRA*, TRB* structure) - I will look into this error more though, it could be something else!

The reason for the multimapping is that the reference has the constant regions, v regions, and j regions separated into different lines (which the aligner recognizes as different chromosomes/contigs), and most reads should map at least two of those regions. During the later steps, it will identify the V and J corresponding to each read based on the multiple locations in the reference to which it aligns. 

I do see alignment rates consistent with what you are seeing. I have not used an updated human reference, but if you know of a newer version I am happy to help with formatting it for this pipeline!

**Comment by ajwilk** [comment]
Thanks @snyquist2!! So removing the deltas and gammas from the reference fasta got me past that previous error, but now I'm stuck in ```call-recover_cdr3s```:

```
================================================================================
18:58:58, 2021-06-21 - TCRGO: Initialized logger, ready for TCRGO.
18:58:58 - INFO: Parsing input data...
18:58:58 - INFO: No index was detected, building index...
18:59:01 - INFO: Reading /cromwell_root/fc-d8b64044-a999-46bf-846b-b52b2a9a1b7c/33d380fe-6f7e-4362-8472-660f91a7f896/TCRGO/ab90f7a0-15d5-4bf3-9329-dce024f1babe/call-alignment/out/pregnancy_test2_repairedsorted.bam...
18:59:01 - INFO: Reading CDR3 positions file and FASTA file...
18:59:01 - ERROR! AE000658|TRAV1-1*01| does not begin with 'TRA' or 'TRB'!
```

How is the reference fasta you're using syntactically constructed? Or better yet, could you share the human reference fasta you're using?

**Comment by snyquist2** [comment]
It looks like the portion of the code reading in that file is specifically looking for fasta sequences to be named with names starting with 'TRA' or 'TRB'.

I've opened an issue to change this so it works with the fasta files from the old pipeline, but as a quick patch, removing the part before the '|' in your fasta should work!

So the syntax would look like this, for example:

```
>TRAJ1
TATGAAGGTGTTACCTCCCAGTAGCAATTTGGCAAAGGAACCAGAGTTTCCATTTCTC
```

**Comment by ajwilk** [comment]
I think we can close this issue now since the alignment issue has been addressed and the remaining discussions concern other issues.
