### ISSUE TITLE
Handling multiple alleles in reference

### ISSUE THREAD

**Issue by ajwilk** [ShalekLab/tcrgo#7]
Running into this error in ```recover-cdr3s```: 

`04:07:14 - ERROR! TRBV5-3*01 and TRBV5-3*02 have same sequence!`

However, these two entries are *not* identical, just nearly identical (one aa mismatch; fasta attached, uploaded as a .txt to directly attach to this issue).
[human_tcr_noGD_reformat_noTRBD_dedup.txt](https://github.com/ShalekLab/tcrgo/files/6902614/human_tcr_noGD_reformat_noTRBD_dedup.txt)

So I have two questions:

1. What degree of overlap is causing this error to be thrown? If you can provide that information I should be able to roughly de-duplicate the reference to get it working. Importantly, other TCR alleles from the same gene that appear together in the reference (eg. in the attached, `TRBV5-1*01` and `TRBV5-1*02`) are sufficiently different that this error is not thrown.
2. In the future perhaps it could be advisable to include a way of handling these alleles. Eg. include the allele specification if aligning to that particular allele, but merely returning the gene without allele specification if it aligns to multiple?

**Comment by snyquist2** [comment]
@ajwilk I've finally identified the problem! I think the pipeline expects that the sequence in the fasta file is stored on a single line (as opposed to a fixed length per line as is standard for fasta files). I realize that the example fastas do not follow this format but am suspicious that they might not have been tested completely. If there are no mismatches in that first line, it might look like the sequences are identical.

I think this function: https://github.com/ShalekLab/tcrgo/blob/b8c71bbfaa27423fa5dab9217100089c4e7de718/tcrgo/io.py#L220 
is the source of the bug.  Currently our system is down for running this pipeline at all so I am unable to debug this or verify that this is actually the issue, but I will post here as soon as it is fixed. In the meantime, a tedious solution would be to again reformat the fasta to include the entire sequence in a single line.


For point two, this situation is indirectly handled by the 'exclude_relatives' argument - setting this to true will allow reads mapping to either allele to be included in CDR3 reconstruction. In theory, for a single UMI there would be at least slightly more reads aligning to the correct allele then mapping to the alternative, so the allele for that UMI would be correctly assigned. If no reads overlapped this mismatch, the pipeline currently assigns the UMI to the allele that comes first alphabetically. Then, you can manually identify these instances with the output file called 'tiebreaks_alignment.tsv' (I now realize this is not documented anywhere) which will list all of the instances where a tie needed to be broken. - Agreed that this process could use some refinement!

**Comment by ajwilk** [comment]
the whole pipeline ran successfully (it appears) using a single line formatted reference fasta, thanks!
